name = "x10"
license = "MIT"
licenselink = "https://github.com/eliasson/markuseliasson/README.md"
description = "A factor10 touch on my theme"
homepage = "http://www.markuseliasson.se"
tags = ["", ""]
features = ["", ""]
min_version = 0.37

[author]
  name = "Markus Eliasson"
  homepage = "http://www.markuseliasson.se"
